version: '3.8'
services:
  gateway:
    build: gateway
    image: gateway-image
    container_name: gateway-container
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - server
    environment:
      # - TZ=Europe/Moscow
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: server-image
    container_name: server-container
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - db
    restart: on-failure
    environment:
      # - TZ=Europe/Moscow
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit_db

  db:
    image: postgres:13.7-alpine
    container_name: postgresql-container
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "6541:5432"
    environment:
      # - TZ=Europe/Moscow
      - POSTGRES_DB=shareit_db
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432